version: '3'
services:
  selenium:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: "python -u tool-twitter.py"
    depends_on:
      - chrome
    networks:
      - tool-auto
    restart: always

  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
    environment:
      - SE_NODE_MAX_SESSIONS=10
    expose:
      - 4444
    networks:
      - tool-auto
    restart: always

networks:
  tool-auto:
    driver: bridge