version: '3'
services:
  selenium:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: "python -u tool-twitter.py"
    depends_on:
      - chrome
      - flask
    networks:
      - tool-auto
    restart: always

  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
    environment:
      - SE_NODE_MAX_SESSIONS=10
      - SE_NODE_SESSION_TIMEOUT=5000
      - SE_SESSION_REQUEST_TIMEOUT=31536000
    expose:
      - 4444
    networks:
      - tool-auto
    restart: always

  flask:
    environment:
      - TELEGRAM_BOT_API=
      - DISCORD_BOT_API=
      - ENV PYTHONUNBUFFERED 1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 80:5000
    command: "gunicorn -b 0.0.0.0:5000 server:app"
    expose:
      - 5000
    networks:
      - tool-auto
    restart: always

networks:
  tool-auto:
    driver: bridge
